volumes:
  ckan_storage:
    driver: local
  solr_data:
    driver: local
  pg_data:
    driver: local

x-common-ckan-env:
  &common-ckan-env
  # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
  CKAN_SQLALCHEMY_URL: postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
  CKAN_DATASTORE_WRITE_URL: postgresql://ckan:${POSTGRES_PASSWORD}@db/datastore
  CKAN_DATASTORE_READ_URL: postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
  CKAN_SOLR_URL: http://solr:8983/solr/ckan
  CKAN_REDIS_URL: redis://redis:6379/1
  CKAN_DATAPUSHER_URL: http://datapusher:8800
  CKAN_MAX_UPLOAD_SIZE_MB: ${CKAN_MAX_UPLOAD_SIZE_MB}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  DS_RO_PASS: ${DATASTORE_READONLY_PASSWORD}
  # DOI
  DOI_PREFIX: ${DOI_PREFIX}
  DOI_ACCOUNT_NAME: ${DOI_ACCOUNT_NAME}
  DOI_ACCOUNT_PWD: ${DOI_ACCOUNT_PWD}
  # Dev
  USERSPEC: root

x-common-ckan:
  &common-ckan
  image: nina-ckan-coat:dev
  depends_on:
    db:
      condition: service_healthy
    solr:
      condition: service_healthy
    redis:
      condition: service_healthy
  volumes:
    #- ckan_storage:/var/lib/ckan
    - ./coat-public/data:/var/lib/ckan
  ports:
    - "${CKAN_PORT}:5000"
  healthcheck:
    test: ["CMD", "wget", "-qO", "/dev/null", "localhost:5000/dataset/"]

x-common-ckan-prod:
  &common-ckan-prod
  << : *common-ckan
  environment:
    << : *common-ckan-env
    CKAN_OAUTH2_AUTHORIZATION_ENDPOINT: ${CKAN_OAUTH2_AUTHORIZATION_ENDPOINT}
    CKAN_OAUTH2_TOKEN_ENDPOINT: ${CKAN_OAUTH2_TOKEN_ENDPOINT}
    CKAN_OAUTH2_CLIENT_ID: ${CKAN_OAUTH2_CLIENT_ID}
    CKAN_OAUTH2_CLIENT_SECRET: ${CKAN_OAUTH2_CLIENT_SECRET}
    DOI_TEST_MODE: false
    ENV: prod

x-common-ckan-dev:
  &common-ckan-dev
  << : *common-ckan
  volumes:
    #- ckan_storage:/var/lib/ckan
    - ./coat-public/data:/var/lib/ckan
    - ./ckanext:/usr/lib/ckan/venv/src/ckanext:ro
    - ./custom/coat-entrypoint.sh:/coat-entrypoint.sh:ro
  entrypoint: ["bash", "coat-entrypoint-dev.sh"]
  environment:
    &common-ckan-env-dev
    << : *common-ckan-env
    DOI_TEST_MODE: true
    ENV: dev

services:
  ckan-prod:
    << : *common-ckan-prod
    profiles:
      - prod

  ckan-dev:
    << : *common-ckan-dev
    profiles:
      - dev
    command: 'python -m pdb -c continue /usr/lib/ckan/venv/bin/ckan --config /etc/ckan/production.ini run --host 0.0.0.0 --passthrough-errors'
    tty: true
    stdin_open: true

  ckan-test:
    << : *common-ckan-dev
    profiles:
      - test
    command: 'ckan --config /etc/ckan/production.ini run --host 0.0.0.0'
    hostname: ckan
    environment:
      << : *common-ckan-env-dev
      CKAN_SITE_URL: http://ckan:5000

  test:
    profiles:
      - test
    image: nina-ckan-coat:test
    depends_on:
      ckan-test:
        condition: service_healthy
    environment:
      CKAN_SITE_URL: http://ckan:5000

  datapusher:
    container_name: datapusher
    image: clementmouchet/datapusher

  db:
    container_name: db
    image: registry.gitlab.com/nina-data/ckan/nina-2-9-py3/postgresql
    environment:
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ckan"]

  solr:
    container_name: solr
    image: ckan/ckan-solr:2.9-solr8
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data
    ports:
      - "8983:8983"
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "localhost:8983/solr/"]

  redis:
    container_name: redis
    image: redis:6
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]
