# docker-compose build && docker-compose up
# If you experience problems with the CKAN container not being
# able to connect to the DB, then most likely the DB has not
# started up quickly enough. Just do "docker-compose up ckan"
# again to retry
##################################################################
# Matteo --> inspired from:
# https://github.com/dbca-wa/ckan/blob/master/contrib/docker/docker-compose.yml
# and from:
# https://github.com/ckan/ckan/blob/master/contrib/docker/docker-compose.yml
version: "3"
services:
  ckan:
    container_name: ckan
    image: registry.gitlab.com/coat-no/ckan-custom/master:f0ef1daf185ce11d36bf7f752bfa5553b71f69b1
    links:
      - db
      - solr
      - redis
    ports:
      - "80:5000"
    environment:
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_SOLR_URL=${CKAN_SOLR_URL}
      - CKAN_REDIS_URL=${CKAN_REDIS_URL}
      - CKAN_DATAPUSHER_URL=${CKAN_REDIS_URL}
      - DB_PORT_5432_TCP_ADDR=db
      - DB_PORT_5432_TCP_PORT=65432
      - SOLR_PORT_8983_TCP_ADDR=solr
      - SOLR_PORT_8983_TCP_PORT=8983
      - REDIS_PORT_6379_TCP_ADDR=redis
  db:
    container_name: db
    image: ckan/postgresql:latest
    ports:
      - "65432:5432"
  solr:
    container_name: solr
    image: ckan/solr:latest
    ports:
      - "8983:8983"
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  datapusher:
    container_name: datapusher
    image: clementmouchet/datapusher
    ports:
      - "8800:8800"
