volumes:
  ckan_storage:
    driver: local
  solr_data:
    driver: local
  pg_data:
    driver: local

x-common-ckan-env:
  &common-ckan-env
  # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
  CKAN_SITE_URL: ${CKAN_SITE_URL}
  CKAN_SQLALCHEMY_URL: postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
  CKAN_DATASTORE_WRITE_URL: postgresql://ckan:${POSTGRES_PASSWORD}@db/datastore
  CKAN_DATASTORE_READ_URL: postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
  CKAN_SOLR_URL: http://solr:8983/solr/ckan
  CKAN_REDIS_URL: redis://redis:6379/1
  CKAN_DATAPUSHER_URL: http://datapusher:8800
  CKAN_MAX_UPLOAD_SIZE_MB: ${CKAN_MAX_UPLOAD_SIZE_MB}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  DS_RO_PASS: ${DATASTORE_READONLY_PASSWORD}
  # DOI
  DOI_PREFIX: ${DOI_PREFIX}
  DOI_ACCOUNT_NAME: ${DOI_ACCOUNT_NAME}
  DOI_ACCOUNT_PWD: ${DOI_ACCOUNT_PWD}
  # Misc
  USERSPEC: ckan

x-common-ckan:
  &common-ckan
  image: nina-ckan-coat:dev
  hostname: ckan
  depends_on:
    - db
    - solr
    - redis
    - nginx
    - pycsw
    - bulk-download
  volumes:
    - &common-ckan-volume
      ckan_storage:/var/lib/ckan
  healthcheck:
    test: ["CMD", "wget", "-qO", "/dev/null", "localhost:5000/dataset/"]

x-common-ckan-prod:
  &common-ckan-prod
  << : *common-ckan
  environment:
    << : *common-ckan-env
    CKAN_OAUTH2_AUTHORIZATION_ENDPOINT: ${CKAN_OAUTH2_AUTHORIZATION_ENDPOINT}
    CKAN_OAUTH2_TOKEN_ENDPOINT: ${CKAN_OAUTH2_TOKEN_ENDPOINT}
    CKAN_OAUTH2_CLIENT_ID: ${CKAN_OAUTH2_CLIENT_ID}
    CKAN_OAUTH2_CLIENT_SECRET: ${CKAN_OAUTH2_CLIENT_SECRET}
    DOI_TEST_MODE: false
    ENV: prod

x-common-ckan-dev:
  &common-ckan-dev
  << : *common-ckan
  volumes:
    - *common-ckan-volume
    - ./ckanext/ckanext-coat/ckanext:/usr/lib/ckan/venv/src/ckanext/ckanext-coat/ckanext:ro
    - ./ckanext/ckanext-coatcustom/ckanext:/usr/lib/ckan/venv/src/ckanext/ckanext-coatcustom/ckanext:ro
    - ./ckanext/ckanext-datasetversions/ckanext:/usr/lib/ckan/venv/src/ckanext/ckanext-datasetversions/ckanext:ro
    - ./ckanext/ckanext-dcat/ckanext:/usr/lib/ckan/venv/src/ckanext/ckanext-dcat/ckanext:ro
    - ./ckanext/ckanext-doi/ckanext:/usr/lib/ckan/venv/src/ckanext/ckanext-doi/ckanext:ro
    - ./ckanext/ckanext-harvest/ckanext:/usr/lib/ckan/venv/src/ckanext/ckanext-harvest/ckanext:ro
    - ./ckanext/ckanext-iso19115/ckanext:/usr/lib/ckan/venv/src/ckanext/ckanext-iso19115/ckanext:ro
    - ./ckanext/ckanext-metaexport/ckanext:/usr/lib/ckan/venv/src/ckanext/ckanext-metaexport/ckanext:ro
    - ./ckanext/ckanext-oauth2/ckanext:/usr/lib/ckan/venv/src/ckanext/ckanext-oauth2/ckanext:ro
    - ./ckanext/ckanext-scheming/ckanext:/usr/lib/ckan/venv/src/ckanext/ckanext-scheming/ckanext:ro
    - ./ckanext/ckanext-spatial/ckanext:/usr/lib/ckan/venv/src/ckanext/ckanext-spatial/ckanext:ro
    - ./custom/coat-entrypoint.sh:/coat-entrypoint.sh:ro
    - ./custom/coat-entrypoint-dev.sh:/coat-entrypoint-dev.sh:ro
  entrypoint: ["bash", "coat-entrypoint-dev.sh"]
  environment:
    &common-ckan-env-dev
    << : *common-ckan-env
    DOI_TEST_MODE: true
    ENV: dev

services:
  ckan-prod:
    << : *common-ckan-prod
    profiles:
      - prod

  ckan-dev:
    << : *common-ckan-dev
    profiles:
      - dev
    command: 'python -m pdb -c continue /usr/lib/ckan/venv/bin/ckan run --host 0.0.0.0 --passthrough-errors'
    tty: true
    stdin_open: true
    environment:
      << : *common-ckan-env-dev
      WERKZEUG_DEBUG_PIN: 5000

  ckan-test:
    << : *common-ckan-dev
    profiles:
      - test
    command: 'ckan run --host 0.0.0.0'
    environment:
      << : *common-ckan-env-dev
      CKAN_SITE_URL: http://ckan:5000

  test:
    profiles:
      - test
    image: nina-ckan-coat:test
    depends_on:
      - ckan-test
    environment:
      COAT_URL: http://nginx
    volumes:
      - ./tests/latest_logs:/app/latest_logs

  datapusher:
    container_name: datapusher
    image: clementmouchet/datapusher

  pycsw:
    build:
      context: services/pycsw
      dockerfile: Dockerfile
    image: ghcr.io/coatnor/coat2pycsw:main
    environment:
      COAT_URL: http://ckan:5000/
      PYCSW_URL: http://localhost/pycsw/csw.py
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "localhost:8000/pycsw/csw.py"]

  bulk-download:
    build:
      context: services/bulk-download
      dockerfile: Dockerfile
    image: ghcr.io/coatnor/coat-bulk-download:main
    environment:
      COAT_URL: http://ckan:5000/
      COAT_PUBLIC_URL: http://127.0.0.1:${CKAN_PORT}/

  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    depends_on:
      - varnish

  varnish:
    build:
      context: services/varnish
      dockerfile: Dockerfile
    ports:
      - "${CKAN_PORT}:80"

  db:
    image: registry.gitlab.com/nina-data/ckan/nina-ckan-2-9-7/postgresql
    environment:
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ckan"]

  solr:
    image: ckan/ckan-solr:2.9-solr8
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data
    ports:
      - "8983:8983"
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "localhost:8983/solr/"]

  redis:
    image: redis:6
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]
