volumes:
  ckan_storage:
    driver: local
  solr_data:
    driver: local
  pg_data:
    driver: local

x-common-ckan:
  &default-common-ckan
  image: nina-ckan-coat:dev
  depends_on:
    - db
    - solr
    - redis
    - datapusher
  environment:
    &default-common-env-ckan
    # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
    CKAN_SQLALCHEMY_URL: postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
    CKAN_DATASTORE_WRITE_URL: postgresql://ckan:${POSTGRES_PASSWORD}@db/datastore
    CKAN_DATASTORE_READ_URL: postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
    CKAN_SOLR_URL: http://solr:8983/solr/ckan
    CKAN_REDIS_URL: redis://redis:6379/1
    CKAN_DATAPUSHER_URL: http://datapusher:8800
    CKAN_SITE_URL: ${CKAN_SITE_URL}
    CKAN_MAX_UPLOAD_SIZE_MB: ${CKAN_MAX_UPLOAD_SIZE_MB}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    DS_RO_PASS: ${DATASTORE_READONLY_PASSWORD}
    CKAN_OAUTH2_AUTHORIZATION_ENDPOINT: ${CKAN_OAUTH2_AUTHORIZATION_ENDPOINT}
    CKAN_OAUTH2_TOKEN_ENDPOINT: ${CKAN_OAUTH2_TOKEN_ENDPOINT}
    CKAN_OAUTH2_CLIENT_ID: ${CKAN_OAUTH2_CLIENT_ID}
    CKAN_OAUTH2_CLIENT_SECRET: ${CKAN_OAUTH2_CLIENT_SECRET}
    # Mode (dev or prod)
    ENV: ${ENV}
    # DOI
    DOI_PREFIX: ${DOI_PREFIX}
    DOI_ACCOUNT_NAME: ${DOI_ACCOUNT_NAME}
    DOI_ACCOUNT_PWD: ${DOI_ACCOUNT_PWD}
    DOI_TEST_MODE: ${DOI_TEST_MODE}
    # docker-compose-wait
    WAIT_HOSTS_TIMEOUT: 180
    WAIT_SLEEP_INTERVAL: 10
    # Dev
    USERSPEC: root
  volumes:
    - ckan_storage:/var/lib/ckan
    - ./ckanext:/usr/lib/ckan/venv/src/ckanext

services:
  ckan:
    << : *default-common-ckan
    container_name: ckan
    ports:
      - "${CKAN_PORT}:5000"
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "localhost:5000/dataset/"]
    # Debug with pdb
    #command: 'python -m pdb /usr/lib/ckan/venv/bin/ckan --config /etc/ckan/production.ini run --host 0.0.0.0 --passthrough-errors'
    #tty: true
    #stdin_open: true

  datapusher:
    container_name: datapusher
    image: clementmouchet/datapusher
    ports:
      - "8800:8800"

  db:
    container_name: db
    image: registry.gitlab.com/nina-data/ckan/nina-2-9-py3/postgresql
    environment:
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ckan"]

  solr:
    container_name: solr
    image: ckan/ckan-solr:2.9-solr8
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data
    ports:
      - "8983:8983"
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "localhost:8983/solr/"]

  redis:
    container_name: redis
    image: redis:6
