# docker-compose build && docker-compose up -d
# If "docker-compose logs ckan" shows DB not ready, run "docker-compose restart ckan" a few times.
##################################################################
# Matteo De Stefano, Francesco Frassinelli - Derived from:
#   https://github.com/ckan/ckan/blob/master/contrib/docker/docker-compose.yml

version: "3.0"

# Driver has to be specified because of https://github.com/docker/libcompose/issues/509
volumes:
#  ckan_config:
#    driver: local
#  ckan_home:
#    driver: local
  ckan_storage:
    driver: local
  solr_data:
    driver: local
  pg_data:
    driver: local
{% block volumes %}{% endblock %}

services:
  ckan:
    container_name: ckan
    image: registry.gitlab.com/nina-data/nina-ckan-coat/master
    build:
      context: .
    links:
      - db
      - solr
      - redis
      - datapusher
    depends_on:
      - db
    ports:
      - "${CKAN_PORT}:5000"
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_DATAPUSHER_URL=http://datapusher:8800
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
{% for ext in extensions if target in ext.targets and ext.settings_set_startup %}
{% for section, key, value in ext.settings_set_startup %}
      - {{ value }}={{ "${"+value+"}" }}
{% endfor %}
{% endfor %}
    volumes:
#      - ckan_config:/etc/ckan
#      - ckan_home:/usr/lib/ckan
      - ckan_storage:/var/lib/ckan
{% block ckan_volumes %}{% endblock %}
{% for ext in extensions if target in ext.targets and ext.local %}
      - {{ extensions_path }}/{{ ext.repository }}:/usr/lib/ckan/venv/src/{{ ext.name }}
{% endfor %}
#    restart: unless-stopped # https://github.com/ckan/ckan/issues/4514
    stdin_open: true
    tty: true

  datapusher:
    container_name: datapusher
    image: clementmouchet/datapusher
    ports:
      - "8800:8800"

  db:
    container_name: db
    image: registry.gitlab.com/nina-data/ckan/nina-2-8-3/postgresql
    environment:
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ckan"]

  solr:
    container_name: solr
    image: registry.gitlab.com/nina-data/ckan/nina-2-8-3/solr
    volumes:
      - solr_data:/opt/solr/server/solr/ckan
    ports:
      - "8983:8983"

  redis:
    container_name: redis
    image: redis:latest

  checker:
    image: busybox
    command: sh -c 'while true; do wget "http://ckan:5000/dataset/" -O /dev/null -o /dev/null || echo "[`date`] error"; sleep 3m; done'

{% include "docker-compose-custom/"+target ignore missing %}

{% block containers %}{% endblock %}
