# docker-compose build && docker-compose up -d
# If "docker-compose logs ckan" shows DB not ready, run "docker-compose restart ckan" a few times.
##################################################################
# Matteo De Stefano, Francesco Frassinelli - Derived from:
#   https://github.com/ckan/ckan/blob/master/contrib/docker/docker-compose.yml

# Workaround for https://github.com/portainer/portainer/issues/2345#issuecomment-428197441
version: "2"

# Driver has to be specified because of https://github.com/docker/libcompose/issues/509
volumes:
#  ckan_config:
#    driver: local
#  ckan_home:
#    driver: local
  ckan_storage:
    driver: local
  pg_data:
    driver: local

services:
  ckan:
    container_name: ckan
    image: registry.gitlab.com/nina-data/nina-ckan-coat:latest
    build:
      context: .
    links:
      - db
      - solr
      - redis
    ports:
      - "${CKAN_PORT}:5000"
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_DATAPUSHER_URL=http://datapusher:8800
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
    volumes:
#      - ckan_config:/etc/ckan
#      - ckan_home:/usr/lib/ckan
      - ckan_storage:/var/lib/ckan
{% for ext in extensions if target in ext.targets and ext.local %}
      - ../../{{ ext.repository }}:/usr/lib/ckan/venv/src/{{ ext.name }}
{% endfor %}

  datapusher:
    container_name: datapusher
    image: clementmouchet/datapusher
    ports:
      - "8800:8800"

  db:
    container_name: db
    image: ckan/postgresql:latest
    environment:
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    image: ckan/solr:latest

  redis:
    container_name: redis
    image: redis:latest
