- name: ckanext-spatial
  repository: https://github.com/ckan/ckanext-spatial
  version: master
  settings_add:
    ckan.plugins: spatial_metadata spatial_query
  settings_set:
    ckanext.spatial.search_backend: solr
  targets:
    - dev
    - deploy
#- name: ckanext-geoview
#  repository: https://github.com/ckan/ckanext-geoview
#  version: v0.0.13
#  settings_add:
#    ckan.plugins: resource_proxy geojson_view
#  settings_set:
#    ckan.views.default_views: geojson_view
#  targets:
#    - dev
#    - deploy
- name: ckanext-harvest
  repository: https://github.com/ckan/ckanext-harvest
  version: v1.1.1
  settings_add:
    ckan.plugins: harvest ckan_harvester
  targets:
    - dev
    - deploy
- name: ckanext-dcat
  repository: https://github.com/ckan/ckanext-dcat
  version: v0.0.7
  settings_add:
    ckan.plugins: dcat dcat_rdf_harvester dcat_json_interface structured_data
  targets:
    - dev
    - deploy
- name: ckanext-ldap
  repository: https://github.com/NaturalHistoryMuseum/ckanext-ldap.git
  version: ckan-upgrade-2.8.0a
  packages:
    - libsasl2-dev
    - python-dev
    - libldap2-dev
    - libssl-dev
  settings_add:
    ckan.plugins: ldap
  settings_set:
    ckanext.ldap.uri: ldap://nindc05.nina.no:389
    ckanext.ldap.auth.dn: ldapquery
    ckanext.ldap.base_dn: ou=brukere,dc=nina,dc=no
    ckanext.ldap.search.filter: sAMAccountName={login}
    ckanext.ldap.username: sAMAccountName
    ckanext.ldap.email: mail
    ckanext.ldap.ckan_fallback: true
  settings_set_startup:
    ckanext.ldap.auth.password: LDAP_PASSWORD
  targets:
    - dev
    - deploy
- name: ckanext-coat
  repository: https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.com/nina-data/ckanext-coat.git
  version: master
  settings_add:
    ckan.plugins: coat
  targets:
    - deploy
- name: ckanext-coat
  local: true
  repository: ckanext-coat
  settings_add:
    ckan.plugins: coat
  targets:
    - dev
- name: config
  settings_set:
    ckan.site_title: COAT catalog
    ckan.site_intro_text: "# Welcome to the COAT catalog"
    ckan.site_logo: "https://www.coat.no/Portals/coat/Images/cropped-coat_logo_black2014_tr.png"
  targets:
    - dev
    - deploy